language: csharp
solution: TvMazeScraper/TvMazeScraper.sln
install:
  - nuget restore TvMazeScraper/TvMazeScraper.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TvMazeScraper/TvMazeScraper.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TvMazeScraper.Tests/bin/Release/TvMazeScraper.Tests.dll
